import 'dotenv/config';
import { Client, GatewayIntentBits, REST, Routes, SlashCommandBuilder, EmbedBuilder, PermissionFlagsBits, ActionRowBuilder, StringSelectMenuBuilder, ButtonBuilder, ButtonStyle, ChatInputCommandInteraction, GuildMember, ChannelType } from 'discord.js';
import { db, getSettings, saveSetting } from './db.js';
import { buildServer, setupPreview } from './server-setup.js';

const token = process.env.DISCORD_TOKEN;
if (!token) throw new Error('DISCORD_TOKEN fehlt. Lege eine .env-Datei an.');
const guildId = process.env.DISCORD_GUILD_ID;
const clientId = process.env.DISCORD_CLIENT_ID;
const colors = { red: 0xd90429, blue: 0x1261a0, green: 0x2a9d8f, gold: 0xf4a261 };
const commands = [
 new SlashCommandBuilder().setName('notruf').setDescription('Erstellt einen neuen Notruf').addStringOption(o=>o.setName('kategorie').setDescription('Art des Notrufs').setRequired(true).addChoices(...['Polizei','Feuerwehr','Rettungsdienst','Verkehrsunfall','Sonstiger Notfall'].map(x=>({name:x,value:x} as const)))).addStringOption(o=>o.setName('ort').setDescription('Einsatzort').setRequired(true)).addStringOption(o=>o.setName('beschreibung').setDescription('Beschreibung').setRequired(true)),
 new SlashCommandBuilder().setName('einsatz').setDescription('Verwaltet einen Einsatz').addSubcommand(s=>s.setName('status').setDescription('Status ändern').addIntegerOption(o=>o.setName('nummer').setDescription('Einsatznummer').setRequired(true)).addStringOption(o=>o.setName('wert').setDescription('Neuer Status').setRequired(true).addChoices(...['Offen','Angenommen','In Bearbeitung','Abgeschlossen'].map(x=>({name:x,value:x} as const))))).addSubcommand(s=>s.setName('uebernehmen').setDescription('Einsatz übernehmen').addIntegerOption(o=>o.setName('nummer').setDescription('Einsatznummer').setRequired(true))).addSubcommand(s=>s.setName('melden').setDescription('Sich zu einem Einsatz melden').addIntegerOption(o=>o.setName('nummer').setDescription('Einsatznummer').setRequired(true))),
 new SlashCommandBuilder().setName('dienst').setDescription('Dienststatus verwalten').addSubcommand(s=>s.setName('status').setDescription('Status setzen').addStringOption(o=>o.setName('abteilung').setDescription('Abteilung').setRequired(true).addChoices(...['Polizei','Feuerwehr','Rettungsdienst'].map(x=>({name:x,value:x} as const)))).addStringOption(o=>o.setName('wert').setDescription('Status').setRequired(true).addChoices(...['Verfügbar','Im Einsatz','Pause','Nicht im Dienst'].map(x=>({name:x,value:x} as const))))).addSubcommand(s=>s.setName('liste').setDescription('Aktive Dienstkräfte anzeigen')),
 new SlashCommandBuilder().setName('rp').setDescription('RP-Profil verwalten').addSubcommand(s=>s.setName('profil').setDescription('Profil speichern').addStringOption(o=>o.setName('name').setDescription('RP-Name').setRequired(true)).addStringOption(o=>o.setName('fraktion').setDescription('Fraktion')).addStringOption(o=>o.setName('rang').setDescription('Rang'))).addSubcommand(s=>s.setName('anzeigen').setDescription('Profil anzeigen').addUserOption(o=>o.setName('mitglied').setDescription('Mitglied'))),
 new SlashCommandBuilder().setName('punkte').setDescription('Punktesystem').addSubcommand(s=>s.setName('anzeigen').setDescription('Punkte anzeigen').addUserOption(o=>o.setName('mitglied').setDescription('Mitglied'))).addSubcommand(s=>s.setName('leaderboard').setDescription('Rangliste anzeigen')),
 new SlashCommandBuilder().setName('ticket').setDescription('Ticket-Menü im aktuellen Kanal posten'),
 new SlashCommandBuilder().setName('info').setDescription('Serverstatistiken anzeigen'),
 new SlashCommandBuilder().setName('server-setup').setDescription('Vollständiges Nutruf-Hamburg-RP-Server-Setup').setDefaultMemberPermissions(PermissionFlagsBits.Administrator).addStringOption(o=>o.setName('team-rolle').setDescription('ID einer vorhandenen Team-Rolle')).addStringOption(o=>o.setName('on-duty-rolle').setDescription('ID einer vorhandenen On-Duty-Rolle')).addStringOption(o=>o.setName('moderations-rolle').setDescription('ID einer vorhandenen Moderations-Rolle')),
 new SlashCommandBuilder().setName('setup').setDescription('Bot konfigurieren').setDefaultMemberPermissions(PermissionFlagsBits.Administrator).addSubcommand(s=>s.setName('server').setDescription('Kategorien und Kanäle einrichten').addStringOption(o=>o.setName('team-rolle').setDescription('ID einer vorhandenen Team-Rolle')).addStringOption(o=>o.setName('on-duty-rolle').setDescription('ID einer vorhandenen On-Duty-Rolle'))).addSubcommand(s=>s.setName('kanaele').setDescription('Zusätzliche Kanal-ID speichern').addStringOption(o=>o.setName('typ').setDescription('Kanaltyp').setRequired(true).addChoices({name:'Einsätze',value:'emergency_channel'},{name:'Logs',value:'log_channel'},{name:'Bewerbungen',value:'application_channel'})).addStringOption(o=>o.setName('kanal-id').setDescription('Discord-Kanal-ID').setRequired(true))),
 new SlashCommandBuilder().setName('moderation').setDescription('Moderationsaktionen').setDefaultMemberPermissions(PermissionFlagsBits.ModerateMembers).addSubcommand(s=>s.setName('timeout').setDescription('Mitglied timeouten').addUserOption(o=>o.setName('mitglied').setDescription('Mitglied').setRequired(true)).addIntegerOption(o=>o.setName('minuten').setDescription('Dauer in Minuten').setRequired(true)).addStringOption(o=>o.setName('grund').setDescription('Grund'))).addSubcommand(s=>s.setName('clear').setDescription('Nachrichten löschen').addIntegerOption(o=>o.setName('anzahl').setDescription('Anzahl 1-100').setRequired(true)))
].map(c=>c.toJSON());

const embed = (title:string, description:string, color=colors.blue) => new EmbedBuilder().setTitle(title).setDescription(description).setColor(color).setTimestamp().setFooter({text:'Nutruf Hamburg RP'});
const isResponder = (i: { guildId: string | null; member: any }) => { if (!i.guildId) return false; const roles = getSettings(i.guildId).responder_roles; return Object.values(roles).some(r=>r && i.member?.roles?.cache?.has(r)) || i.member?.permissions?.has(PermissionFlagsBits.ManageGuild); };
async function log(i: { guildId: string | null; guild?: any; user: { tag: string } }, text:string) { const channelId=i.guildId ? getSettings(i.guildId).log_channel : undefined; if (channelId && i.guild) { const c=await i.guild.channels.fetch(channelId).catch(()=>null); if (c?.isTextBased() && 'send' in c) await c.send({embeds:[embed('Protokoll',text,colors.gold)]}).catch(()=>{}); } }

const client = new Client({ intents:[GatewayIntentBits.Guilds, GatewayIntentBits.GuildMembers] });
client.once('ready', async c => { console.log(`Online als ${c.user.tag}`); const rest=new REST({version:'10'}).setToken(token); if (guildId && clientId) await rest.put(Routes.applicationGuildCommands(clientId,guildId),{body:commands}); else if(clientId) await rest.put(Routes.applicationCommands(clientId),{body:commands}); });
client.on('interactionCreate', async i => {
 try {
  if (i.isButton() && i.customId==='server-setup:confirm') { if (!i.member || !(i.member as GuildMember).permissions.has(PermissionFlagsBits.Administrator)) return i.reply({content:'Nur Administratoren dürfen das Server-Setup bestätigen.',ephemeral:true}); await i.deferUpdate(); const s=getSettings(i.guildId! ) as any; const result=await buildServer(i.guild!,s.team_role_id||undefined,s.onduty_role_id||undefined,s.mod_role_id||undefined); await i.editReply({embeds:[embed('Server eingerichtet',`**${result.created.length}** Elemente erstellt, **${result.existing.length}** vorhandene Elemente wiederverwendet.${result.incompatible.length?`\nNicht geändert wegen abweichendem Typ: ${result.incompatible.join(', ')}`:''}`,colors.green)],components:[]}); return; }
  if (i.isButton() && i.customId.startsWith('einsatz:')) { const [_,action,id]=i.customId.split(':'); if (!isResponder(i)) return i.reply({content:'Dafür fehlen dir die Berechtigungen.',ephemeral:true}); if(action==='take') db.prepare("UPDATE emergencies SET status='Angenommen', assignee_id=? WHERE id=? AND guild_id=?").run(i.user.id,id,i.guildId); if(action==='close') db.prepare("UPDATE emergencies SET status='Abgeschlossen', closed_at=? WHERE id=? AND guild_id=?").run(new Date().toISOString(),id,i.guildId); await i.update({embeds:[embed('Einsatz aktualisiert',`Einsatz **#${id}** wurde von <@${i.user.id}> bearbeitet.`,colors.green)],components:[]}); await log(i,`Einsatz #${id}: ${action} durch ${i.user.tag}`); return; }
  if (i.isStringSelectMenu() && i.customId==='ticket:create') { const ch=await i.guild?.channels.create({name:`ticket-${i.user.username}`}); await i.reply({content:`Ticket erstellt: ${ch}`,ephemeral:true}); if(ch?.isTextBased()) await ch.send({embeds:[embed('Ticket geöffnet',`Hallo ${i.user}, beschreibe dein Anliegen. Ein Teammitglied meldet sich bald.`)],components:[new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setCustomId('ticket:close').setLabel('Ticket schließen').setStyle(ButtonStyle.Danger))]}); return; }
  if (i.isButton() && i.customId==='ticket:close') { await i.reply({embeds:[embed('Ticket geschlossen','Dieses Ticket wird nun geschlossen.',colors.red)]}); setTimeout(()=>i.channel?.delete().catch(()=>{}),3000); return; }
  if (!i.isChatInputCommand() || !i.guildId) return;
  if (i.commandName==='server-setup') { const preview=setupPreview(); const row=new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setCustomId('server-setup:confirm').setLabel('Setup jetzt bestätigen').setStyle(ButtonStyle.Success)); await i.reply({embeds:[embed('Server-Setup Vorschau',`${preview.slice(0,3900)}\n\n**Vorhandene Kanäle werden wiederverwendet. Rollen werden nicht erstellt.**`,colors.gold)],components:[row],ephemeral:true}); const team=i.options.getString('team-rolle'), duty=i.options.getString('on-duty-rolle'), mod=i.options.getString('moderations-rolle'); if(team) saveSetting(i.guildId,'team_role_id',team); if(duty) saveSetting(i.guildId,'onduty_role_id',duty); if(mod) saveSetting(i.guildId,'mod_role_id',mod); return; }
  if (i.commandName==='notruf') { const cat=i.options.getString('kategorie',true), ort=i.options.getString('ort',true), desc=i.options.getString('beschreibung',true); const r=db.prepare('INSERT INTO emergencies (guild_id,category,location,description,creator_id,created_at) VALUES (?,?,?,?,?,?)').run(i.guildId,cat,ort,desc,i.user.id,new Date().toISOString()); const id=Number(r.lastInsertRowid); const target=getSettings(i.guildId).emergency_channel; const e=embed(`Notruf #${id} — ${cat}`,`**Ort:** ${ort}\n**Beschreibung:** ${desc}\n**Status:** Offen\n**Erstellt von:** ${i.user}`,colors.red); const row=new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setCustomId(`einsatz:take:${id}`).setLabel('Übernehmen').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId(`einsatz:close:${id}`).setLabel('Abschließen').setStyle(ButtonStyle.Success)); if(target) { const ch=await i.guild!.channels.fetch(target); if(ch?.isTextBased()) await ch.send({embeds:[e],components:[row]}); } await i.reply({embeds:[embed('Notruf aufgenommen',`Dein Notruf wurde als **#${id}** erfasst.`,colors.green)],ephemeral:true}); await log(i,`Neuer Notruf #${id} (${cat}) am Ort ${ort}`); return; }
  if (i.commandName==='einsatz') { if(!isResponder(i)) return i.reply({content:'Nur berechtigte Einsatzkräfte dürfen Einsätze verwalten.',ephemeral:true}); const sub=i.options.getSubcommand(), id=i.options.getInteger('nummer',true); if(sub==='status') db.prepare('UPDATE emergencies SET status=? WHERE id=? AND guild_id=?').run(i.options.getString('wert',true),id,i.guildId); if(sub==='uebernehmen') db.prepare("UPDATE emergencies SET status='Angenommen',assignee_id=? WHERE id=? AND guild_id=?").run(i.user.id,id,i.guildId); if(sub==='melden') db.prepare('UPDATE emergencies SET assignee_id=? WHERE id=? AND guild_id=?').run(i.user.id,id,i.guildId); await i.reply({embeds:[embed('Einsatz aktualisiert',`Einsatz **#${id}** wurde bearbeitet.`,colors.green)]}); await log(i,`Einsatz #${id} durch ${i.user.tag} aktualisiert`); return; }
  if (i.commandName==='dienst') { const sub=i.options.getSubcommand(); if(sub==='status') { const dep=i.options.getString('abteilung',true), status=i.options.getString('wert',true); db.prepare('INSERT INTO duty(guild_id,user_id,department,status,started_at) VALUES(?,?,?,?,?) ON CONFLICT(guild_id,user_id,department) DO UPDATE SET status=excluded.status,started_at=excluded.started_at').run(i.guildId,i.user.id,dep,status,status==='Nicht im Dienst'?null:new Date().toISOString()); const dutyRole=(getSettings(i.guildId) as any).onduty_role_id; const member=await i.guild!.members.fetch(i.user.id); if (dutyRole) { if (status==='Nicht im Dienst') await member.roles.remove(dutyRole).catch(()=>{}); else await member.roles.add(dutyRole).catch(()=>{}); } await i.reply({embeds:[embed('Dienststatus gespeichert',`${dep}: **${status}**`,colors.green)]}); } else { const rows=db.prepare("SELECT * FROM duty WHERE guild_id=? AND status!='Nicht im Dienst'").all(i.guildId) as any[]; await i.reply({embeds:[embed('Aktive Einsatzkräfte',rows.length?rows.map(x=>`<@${x.user_id}> — ${x.department}: **${x.status}**`).join('\n'):'Niemand ist derzeit im Dienst.')]}); } return; }
  if (i.commandName==='rp') { const sub=i.options.getSubcommand(), uid=i.options.getUser('mitglied')?.id??i.user.id; if(sub==='profil') { db.prepare('INSERT INTO profiles(guild_id,user_id,rp_name,department,rank) VALUES(?,?,?,?,?) ON CONFLICT(guild_id,user_id) DO UPDATE SET rp_name=excluded.rp_name,department=excluded.department,rank=excluded.rank').run(i.guildId,i.user.id,i.options.getString('name',true),i.options.getString('fraktion'),i.options.getString('rang')); await i.reply({embeds:[embed('RP-Profil gespeichert','Dein Profil wurde aktualisiert.',colors.green)]}); } else { const p=db.prepare('SELECT * FROM profiles WHERE guild_id=? AND user_id=?').get(i.guildId,uid) as any; await i.reply({embeds:[p?embed('RP-Profil',`**Name:** ${p.rp_name}\n**Fraktion:** ${p.department??'—'}\n**Rang:** ${p.rank??'—'}\n**Status:** ${p.rp_status}`):embed('Kein Profil','Für dieses Mitglied ist noch kein RP-Profil gespeichert.',colors.gold)]}); } return; }
  if (i.commandName==='punkte') { const sub=i.options.getSubcommand(); if(sub==='anzeigen') { const uid=i.options.getUser('mitglied')?.id??i.user.id; const p=db.prepare('SELECT value FROM points WHERE guild_id=? AND user_id=?').get(i.guildId,uid) as any; await i.reply({embeds:[embed('Punkte',`<@${uid}> hat **${p?.value??0} Punkte**.`)]}); } else { const rows=db.prepare('SELECT user_id,value FROM points WHERE guild_id=? ORDER BY value DESC LIMIT 10').all(i.guildId) as any[]; await i.reply({embeds:[embed('Punkte-Leaderboard',rows.length?rows.map((x,n)=>`${n+1}. <@${x.user_id}> — **${x.value}** Punkte`).join('\n'):'Noch keine Punkte vergeben.',colors.gold)]}); } return; }
  if (i.commandName==='ticket') { await i.reply({embeds:[embed('Nutruf Hamburg RP — Tickets','Wähle eine Kategorie aus, um ein Ticket zu erstellen.')],components:[new ActionRowBuilder<StringSelectMenuBuilder>().addComponents(new StringSelectMenuBuilder().setCustomId('ticket:create').setPlaceholder('Ticket-Kategorie auswählen').addOptions(['Support','Bewerbung','Fraktion','Beschwerde','Sonstiges'].map(x=>({label:x,value:x.toLowerCase()}))))]}); return; }
  if (i.commandName==='info') { const g=i.guild, active=(db.prepare("SELECT COUNT(*) as n FROM duty WHERE guild_id=? AND status!='Nicht im Dienst'").get(i.guildId) as any).n, calls=(db.prepare('SELECT COUNT(*) as n FROM emergencies WHERE guild_id=?').get(i.guildId) as any).n; await i.reply({embeds:[embed('Nutruf Hamburg RP',`**Mitglieder:** ${g?.memberCount??0}\n**Aktive Einsatzkräfte:** ${active}\n**Einsätze gesamt:** ${calls}\n**Botstatus:** Online`,colors.blue)]}); return; }
  if (i.commandName==='setup') { const sub=i.options.getSubcommand(); if(sub==='server') { await i.deferReply({ephemeral:true}); const result=await buildServer(i.guild!,i.options.getString('team-rolle')??undefined,i.options.getString('on-duty-rolle')??undefined); await i.editReply({embeds:[embed('Server eingerichtet',`Es wurden **${result.categories} Kategorien** und **${result.created.length+result.existing.length} Kanäle** geprüft bzw. erstellt. Vorhandene Rollen wurden nicht verändert.`,colors.green)]}); } else { saveSetting(i.guildId,i.options.getString('typ',true),i.options.getString('kanal-id',true)); await i.reply({embeds:[embed('Setup gespeichert','Die Kanal-Einstellung wurde gespeichert.',colors.green)],ephemeral:true}); } return; }
  if (i.commandName==='moderation') { const sub=i.options.getSubcommand(); if(sub==='timeout') { const m=i.options.getMember('mitglied') as GuildMember, mins=i.options.getInteger('minuten',true), reason=i.options.getString('grund')??'Kein Grund angegeben'; await m.timeout(mins*60*1000,reason); await i.reply({embeds:[embed('Timeout vergeben',`${m} wurde für **${mins} Minuten** timeoutet.\n**Grund:** ${reason}`,colors.red)]}); await log(i,`Timeout: ${m.user.tag} für ${mins} Minuten — ${reason}`); } else { const n=Math.min(100,Math.max(1,i.options.getInteger('anzahl',true))); const msgs=await i.channel?.messages.fetch({limit:n}); if(msgs && i.channel && 'bulkDelete' in i.channel) await i.channel.bulkDelete(msgs,true); await i.reply({content:`${msgs?.size??0} Nachrichten gelöscht.`,ephemeral:true}); } }
 } catch(e) { console.error(e); if(i.isRepliable()) await i.reply({content:'Es ist ein unerwarteter Fehler aufgetreten. Prüfe die Bot-Logs.',ephemeral:true}).catch(()=>{}); }
});
client.on('voiceStateUpdate', async (oldState, newState) => { try { const guild=newState.guild; const settings=getSettings(guild.id) as any; const lobbyId=settings.team_lobby_channel; if (!lobbyId || newState.channelId!==lobbyId) { if (oldState.channel?.name.startsWith('support-') && oldState.channel.members.size===0) await oldState.channel.delete().catch(()=>{}); return; } const roleId=settings.team_role_id || settings.onduty_role_id; const member=newState.member; const isTeam=Boolean(roleId && member?.roles.cache.has(roleId)); const others=newState.channel?.members.filter(m=>m.id!==member?.id); if (!isTeam && others?.size===0) return; const parent=newState.channel?.parent; const temp=await guild.channels.create({name:`support-${Date.now().toString().slice(-4)}`,type:ChannelType.GuildVoice,parent:parent?.id,permissionOverwrites:[{id:guild.roles.everyone.id,deny:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.Connect]},{id:member!.id,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.Connect,PermissionFlagsBits.Speak]}].concat(roleId?[{id:roleId,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.Connect,PermissionFlagsBits.Speak]}]:[])}); await member?.voice.setChannel(temp); for (const [,person] of (others??new Map()).entries()) await person.voice.setChannel(temp).catch(()=>{}); } catch (e) { console.error('Warteraum:',e); } });
client.login(token);
